# -*- coding: utf-8 -*-
"""W01T01_walkthrough.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cy7YihhP7-CG_Qu6i2Qr9jBhTu4p3IuO

# Week 1 · Topic 1 — Your First Program

**Box we are building: OUTPUT**


By the end of this notebook you can make a program say something.

> **Already know this?** Skip to the bottom and do the *Topic 1 Challenge*, then help a neighbour.

---
## 1. print()

`print()` puts something on the screen. Run the next cell.
"""

print("Record check starting")

"""Text inside quotes is a **string**. Single or double quotes both work."""

print('single quotes')
print("double quotes")

"""### Your turn
Make the next cell print your own name.
"""

print("Enrica")

"""---
## 2. Printing several things

Commas put a single space between the values.
"""

print("Record", "R-004", "checked")

print("Value", 23.7)

"""### Your turn
Print `Module CST1510 starts now` using **three** separate values and commas.
"""

print('Module','CST1510','starts now')

"""---
## 3. Blank lines and separators

`print()` on its own prints an empty line.

Multiplying a string repeats it — this is how you draw a line without typing it out.
"""

print("=" * 34)
print("  RECORD CHECK")
print("=" * 34)

print("top")
print()
print("bottom")

"""### Your turn
Print a line of **50 dashes**, then your name, then another 50 dashes.
"""

print('-'*50)
print('Enrica')
print('-'*50)

"""---
## 4. Escape sequences

`\n` starts a new line. `\t` inserts a tab.
"""

print("line one\nline two")

print("ID\tVALUE")
print("R-004\t23.7")

"""### Your turn
Using **one** `print()`, produce exactly:

```
ID	STATUS
R-004	OK
```
"""

print('ID\tSTATUS\nR-004\tOK')

"""---
## 5. Comments

Anything after `#` is ignored by Python. Comments are for the human reading your code — including you, in three weeks.
"""

# Show the report header
print("=" * 20)

"""---
## Topic 1 Challenge

Reproduce this exactly, using only what is in this notebook:

```
==============================
        RECORD CHECK
==============================
```

The title should be centred by eye — count your spaces.
"""

# your code here
print("="*20)
print("    RECORD CHECK")
print("="*20)

"""---
## Same idea, three fields

`print()` is how a program reports what it found.

| Field | Looks like |
|---|---|
| **AI / Data Science** | `Rows loaded: 1200` |
| **Cyber Security** | `[ALERT] failed login from 10.0.0.5` |
| **IT** | `Backup complete - 4 of 4 servers` |

Different job, same tool.

---
## Common mistakes

| Mistake | What you see | Fix |
|---|---|---|
| `print("hello)` | `SyntaxError` | quotes must come in pairs |
| `Print("hello")` | `NameError` | lowercase `print` — Python is case sensitive |
| `print "hello"` | `SyntaxError` | the brackets are required |
| `'it's fine'` | `SyntaxError` | the apostrophe ends the string — use double quotes |

## Go deeper

`examples/01_print_basics.py` — `sep=`, `end=`, `+` vs f-strings
`examples/02_quotes_and_lines.py` — escaping, triple quotes, `\n`, `\t`, repetition

---
## Recap

| You can now | Using |
|---|---|
| put text on screen | `print("...")` |
| print several values | commas |
| draw a separator | `"=" * 30` |
| control lines and tabs | `\n`, `\t` |
| leave a note | `#` |

**Next:** Topic 2 — storing values so you can use them again.
"""