# -*- coding: utf-8 -*-
"""W01T04_walkthrough.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zX2-Iu8_EYMQOWMugp5y3BnoFeRy7rIi

# Week 1 · Topic 4 — Input, Casting and f-strings

**Boxes: INPUT and OUTPUT, properly**

After this notebook you have everything you need for today's mini-project.

> **Already know this?** Skip to the *Topic 4 Challenge*.

---
## 1. Asking for input
"""

record_id = input("Record ID : ")
print("You entered:", record_id)

"""---
## 2. The one rule that catches everyone

> **`input()` always gives you text. Always. Even when the person types a number.**

Run the next cell and type `23.7`.
"""

value = input("Value : ")

print("You typed:", value)
print("Its type is:", type(value))

"""So this would fail with a `TypeError` — Python received the *characters* `2`, `3`, `.`, `7`, not a number.

Uncomment the line and see for yourself.
"""

print(value + 1)

"""---
## 3. Casting — converting a type

| Function | Turns something into |
|---|---|
| `int()` | whole number |
| `float()` | decimal number |
| `str()` | text |
"""

text = "20"
print(text, type(text))

as_number = int(text)
print(as_number, type(as_number))

"""Usually done in the same line as the input. Read it **inside out**: ask → get text → convert → store."""

value = float(input("Value : "))

print(value + 1)
print(type(value))

"""> **Use `float()` unless you are certain the number is whole.** `int("23.7")` fails with a `ValueError`.

### Your turn
Ask for a number of GB used and a total GB, convert both, and print how many GB are free.
"""

used_gb=float(input("GB used: "))
total_gb=float(input("Total GB: "))
free_gb=total_gb-used_gb
print(free_gb)

"""---
## 4. f-strings

Put `f` before the quotes, then any variable in `{ }`.
"""

record_id = "R-004"
value = 23.7

print(f"Record {record_id} has value {value}")

"""You can calculate inside the braces too."""

limit = 20
print(f"Over the limit by {value - limit}")

"""Forgetting the `f` is the most common slip. This prints the braces themselves:"""

print("Record {record_id}")

"""### Your turn
Using an f-string, print `srv-01 is 87% full` from two variables.
"""

server="srv-01"
usage=87
print(f"{server} is {usage}% full")

"""---
## 5. Formatting — making it look like a report

| Written | Shows | Means |
|---|---|---|
| `{value}` | `23.7` | as is |
| `{value:.2f}` | `23.70` | 2 decimal places |
| `{value:>10}` | `      23.7` | right-aligned in 10 spaces |
| `{value:>10.2f}` | `     23.70` | both |
| `{diff:+.1f}` | `+3.7` | always show the sign |
"""

percent = (value / limit) * 100

print(f"{percent}")
print(f"{percent:.2f}")
print(f"{percent:>12.2f}")

"""Right-alignment is what makes a report line up instead of looking like a mess. Compare these two."""

difference = value - limit

print("--- without alignment ---")
print(f"Value : {value}")
print(f"Limit : {limit}")
print(f"Diff  : {difference}")

print()
print("--- with alignment ---")
print(f"Value : {value:>10.2f}")
print(f"Limit : {limit:>10.2f}")
print(f"Diff  : {difference:>+10.2f}")

"""### Your turn
Print `7 / 3` to exactly **three** decimal places.
"""

print(f"{7/3:.3f}")

"""---
## Topic 4 Challenge

Ask the user for a hostname, GB used and GB total. Then print exactly this shape, aligned:

```
==============================
  DISK REPORT  -  srv-01
==============================
  Used        :      87.00 GB
  Total       :     120.00 GB
  Free        :      33.00 GB
  Percent used:      72.5 %
==============================
```

This is a rehearsal for the mini-project. Get it working now and the lab is straightforward.
"""

hostname=input("Hostname: ")
used_gb=float(input("GB Used: "))
total_gb=float(input("Total GB: "))

free_gb=total_gb-used_gb
percent_used=(used_gb/total_gb)*100

print("="*30)
print(f"  DISK REPORT  -  {hostname}")
print("="*30)
print(f"  Used        :      {used_gb:.2f} GB")
print(f"  Total       :     {total_gb:.2f} GB")
print(f"  Free        :      {free_gb:.2f} GB")
print(f"  Percent used:      {percent_used:.1f} %")

print("="*30)

"""---
## Same idea, three fields

Ask for something, convert it, report it back cleanly.

| Field | Looks like |
|---|---|
| **AI / Data Science** | `f"Mean: {mean:.2f} over {n} rows"` |
| **Cyber Security** | `f"[{level}] {failed} failed logins from {ip}"` |
| **IT** | `f"{hostname:<12} disk {used:>3} %"` |

---
## Common mistakes

| Mistake | What you see | Fix |
|---|---|---|
| `input("n: ") + 1` | `TypeError` | `float(input("n: ")) + 1` |
| `int(input())` when they type `23.7` | `ValueError` | use `float()` |
| `print("Value {v}")` | prints the braces | you forgot the `f` |
| `f"{value:.2}"` | odd result | you meant `.2f` |

## Go deeper

`examples/01_input_and_casting.py` — when to use `int()`, `float()`, or neither
`examples/02_fstrings.py` — decimal places, alignment, a finished report

---
## Recap

| You can now | Using |
|---|---|
| ask for a value | `input("...")` |
| convert it | `int()`, `float()`, `str()` |
| put values in text | `f"...{x}..."` |
| set decimal places | `{x:.2f}` |
| line a report up | `{x:>10.2f}` |

**You now have both boxes for Week 1.** Go and build your own in the lab.
"""