# -*- coding: utf-8 -*-
"""W01T02_walkthrough.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XJ8Q4bJfoxY_AzJzvzr7PVdzqVUGbQD

# Week 1 · Topic 2 — Variables and Types

**Box we are building: a first look at STORE**

By the end of this notebook you can store a value, use it again, and say what type it is.

> **Already know this?** Skip to the *Topic 2 Challenge*.

---
## 1. A variable is a name for a value

Read `=` as **"gets"**, not "equals".
`value = 23.7` means *put 23.7 into value*.
"""

record_id = "R-004"
value = 23.7
limit = 20

print(record_id)
print(value)
print(limit)

"""Once stored, use the **name** wherever you would use the value."""

print(record_id, "has value", value)

"""### Your turn
Store your own name in `student_name` and your course in `course`, then print both in one line.
"""

student_name='Enrica'
course='AI and Data Science'
print(student_name,course)

"""---
## 2. Types

Every value has a type. Ask Python with `type()`.
"""

print(type(record_id))
print(type(value))
print(type(limit))

"""| Type | Means |
|---|---|
| `str` | text |
| `int` | whole number |
| `float` | number with a decimal point |

### The thing that catches everyone

These two print identically. They are **not** the same.
"""

text_twenty = "20"
number_twenty = 20

print(text_twenty)
print(number_twenty)

print(type(text_twenty))
print(type(number_twenty))

"""### Your turn
Run the next cell. **Before you run it**, write down what you expect. Then explain the result to the person next to you.
"""

print("20" + "20")
print(20 + 20)

2020
40

"""---
## 3. Naming

Names should say what the value *is*.

Rules: lowercase, underscores between words, no spaces, cannot start with a digit, cannot be a Python word such as `print`, `if` or `class`.
"""

# hard to read later
v = 23.7
l = 20

# easy to read later
sensor_value = 23.7
sensor_limit = 20

print(v - l)
print(sensor_value - sensor_limit)

"""### Your turn
The next cell has three bad names. Rewrite it with good ones. The output should not change.
"""

x = "srv-01"
y = 87
z = 100
print(x, y, z)

server='srv-01'
value_1=87
value_2=100
print(server,value_1,value_2)

"""---
## 4. Reassigning

A variable can be given a new value. The old one is gone.
"""

checks_done = 0
print(checks_done)

checks_done = 1
print(checks_done)

checks_done = 2
print(checks_done)

"""### Your turn
Without running it, what does this print? Write your answer down, then run it.
"""

a = 5
b = 10
a = b
b = 3
print(a, b)

"""10 3

---
## Topic 2 Challenge

Store these four facts about one server in sensibly named variables, then print a single line reading:

```
srv-01 in London is 87% full
```

- hostname: `srv-01`
- location: `London`
- disk used: `87`
- (you decide what to call the `%` sign)
"""

hostname='srv-01'
location='London'
disk_used=87
percent='%'

print(hostname,'in',location,'is',str(disk_used)+percent,'full')

"""---
## Same idea, three fields

A variable holds one fact about one thing.

| Field | Looks like |
|---|---|
| **AI / Data Science** | `reading = 23.7`, `units = "celsius"` |
| **Cyber Security** | `source_ip = "10.0.0.5"`, `port = 443` |
| **IT** | `hostname = "srv-01"`, `disk_used = 87` |

---
## Common mistakes

| Mistake | What you see | Fix |
|---|---|---|
| `23.7 = value` | `SyntaxError` | the name goes on the **left** |
| `my value = 3` | `SyntaxError` | no spaces — `my_value` |
| using a name you never set | `NameError` | assign it before you use it |
| `"20" + 5` | `TypeError` | text and number — convert first (Topic 4) |

> When something behaves oddly, **print the type**. It is almost always this.

## Go deeper

`examples/01_variables.py` — naming rules, reassignment, order of assignment
`examples/02_types.py` — why the type decides what an operator *does*

---
## Recap

| You can now | Using |
|---|---|
| store a value | `name = value` |
| check a type | `type(x)` |
| tell text from numbers | `"20"` vs `20` |
| name things well | `sensor_value`, not `v` |

**Next:** Topic 3 — doing arithmetic with what you stored.
"""
