# -*- coding: utf-8 -*-
"""W01T03_walkthrough.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kv4olguZuVOh6YTSMeWu4uqc_LFzIO3k

# Week 1 · Topic 3 — Numbers and Arithmetic

**Box we are building: a first look at PROCESS**

This is where a program stops storing and starts working things out.

> **Already know this?** Skip to the *Topic 3 Challenge*.

---
## 1. The operators

Run this and compare all seven at once.
"""

a = 17
b = 5

print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

"""### Your turn
Set `a = 23` and `b = 4` and predict all seven answers **before** running it.
"""

#code
a = 23
b = 4

print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

"""---
## 2. `/` always gives a float

Even when it divides exactly.
"""

print(10 / 2)
print(type(10 / 2))

"""`//` throws away the fraction. `%` gives what is left over."""

print(10 // 3)
print(10 % 3)

"""Together they split a number into parts. This is more useful than it looks."""

total_minutes = 137

hours = total_minutes // 60
minutes = total_minutes % 60

print(total_minutes, "minutes is", hours, "hours and", minutes, "minutes")

"""### Your turn
500 seconds is how many whole minutes, and how many seconds left over?
"""

total_seconds=500
minutes=total_seconds//60
seconds=total_seconds%60
print('In 500 seconds,',minutes,'minutes and',seconds,'seconds are there')

"""One split is useful. Chaining two splits, from the biggest unit down, is what you actually need for a stopwatch or a duration."""

total_seconds = 4831

hours = total_seconds // 3600
remaining = total_seconds % 3600

minutes = remaining // 60
seconds = remaining % 60

print(total_seconds, "seconds =", hours, "hours,", minutes, "minutes,", seconds, "seconds")

"""Same idea twice: split off the biggest unit first with `// 3600` and `% 3600`, then split what is *left over* into minutes and seconds the same way you already did above.

### Your turn
9137 seconds is how many hours, minutes and seconds? Do it in two chained steps, the way the cell above does.
"""

total_seconds=9137
hours=total_seconds//3600
remaining=total_seconds%3600
minutes=remaining//60
seconds=remaining%60
print(total_seconds, "seconds =", hours, "hours,", minutes, "minutes,", seconds, "seconds")

"""---
## 3. Order of operations

Python follows normal maths rules: `**` first, then `*` `/` `//` `%`, then `+` `-`.
"""

print(2 + 3 * 4)
print((2 + 3) * 4)

"""> **Habit worth forming:** use brackets even when you do not need them. They cost nothing and remove all doubt.

### Your turn
The next cell gives the wrong answer. The intention was *(10 plus 6) divided by 2*. Fix it.
"""

print((10 + 6) / 2)

"""---
## 4. The calculation you will write most often

*What share of the whole is this?*
"""

value = 23.7
limit = 20

difference = value - limit
percent = (value / limit) * 100

print("Difference:", difference)
print("Percent of limit:", percent)

"""### Your turn
A server has 87 GB used out of 120 GB.
Calculate and print the percentage used, and how many GB are free.
"""

used_gb=87
total_gb=120
percent_used=(used_gb/total_gb)*100
difference=total_gb-used_gb

print("Percentage Used:",percent_used)
print("GB free:",difference)

"""---
## 5. Shorthand

Changing a variable using its own value is so common it has a short form.
"""

count = 0

count = count + 1     # the long way
print(count)

count += 1            # exactly the same thing
print(count)

count += 5
print(count)

"""### Your turn
Start `total` at 100. Subtract 30, then double it, using the short forms. Print the result.
"""

total=100
total-=30
total*=2
print(total)

"""---
## Topic 3 Challenge

A batch of 250 records was checked. 38 of them failed.

Calculate and print, each on its own line:

- how many passed
- the percentage that failed
- the percentage that passed

Use well-named variables. Do not type any answer you could calculate.
"""

total_records=250
failed_records=38
passed_records=total_records-failed_records

percent_failed=(failed_records/total_records)*100
percent_passed=(passed_records/total_records)*100

print("Records passed:",passed_records)
print("Percentage that failed:",percent_failed)
print("Percentage that passed:",percent_passed)

"""---
## Same idea, three fields

Almost every calculation you write in year one is *"what share of the whole is this?"*

| Field | Question |
|---|---|
| **AI / Data Science** | what percentage of rows are missing a value |
| **Cyber Security** | what percentage of login attempts failed |
| **IT** | what percentage of disk space is used |

All three are `(part / total) * 100`.

---
## Common mistakes

| Mistake | What happens | Fix |
|---|---|---|
| `2 + 3 * 4` when you meant `(2 + 3) * 4` | wrong answer, **no error** | use brackets |
| dividing by zero | `ZeroDivisionError` — program stops | check the total is not 0 |
| expecting `10 / 2` to be `5` | it is `5.0` | `/` always gives a float |
| `3.6999999999999993` | not a bug | format it: `f"{x:.2f}"` |

## Go deeper

`examples/01_operators.py` — all seven operators, `//` and `%`, precedence
`examples/02_calculations.py` — the percentage pattern in all three fields

---
## Recap

| You can now | Using |
|---|---|
| do arithmetic | `+ - * / // % **` |
| split a number into parts | `//` and `%` |
| chain splits into hours, minutes, seconds | `// 3600` / `% 3600`, then `// 60` / `% 60` on what's left |
| control the order | brackets |
| find a percentage | `(part / total) * 100` |
| update a variable | `+=` |

**Next:** Topic 4 — getting values from the user and reporting back.
"""
